apiVersion: v1
kind: Service
metadata:
  name: gom-webservice2
spec:
  selector:
    app: gom-webservices2
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer




#
#  apiVersion: v1
#  kind: Service
#  metadata:
#    finalizers:
#      - service.kubernetes.io/load-balancer-cleanup
#    name: gom-webservices
#    namespace: chip
#  spec:
#    allocateLoadBalancerNodePorts: true
#    externalTrafficPolicy: Cluster
#    internalTrafficPolicy: Cluster
#    ipFamilies:
#      - IPv4
#    ipFamilyPolicy: SingleStack
#    ports:
#      - protocol: TCP
#        port: 3000
#        targetPort: 3000
#    selector:
#      app: gom-webservices
#    sessionAffinity: None
#    type: LoadBalancer
