Rails.application.routes.draw do
  mount Rswag::Api::Engine => '/api-docs'
  mount Rswag::Ui::Engine => '/api-docs'
  get 'api/health_check' => 'application#health_check'


  post '/v0.5/users/auth/on-init' => 'abdm_callback#on_init_auth'
  post '/v0.5/users/auth/on-fetch-modes' => 'abdm_callback#on_fetch_modes'
  post '/v0.5/users/auth/on-confirm' => 'abdm_callback#on_confirm_auth'
  post 'api/fetch-callback-data' => 'abdm_callback#read_callback'
  post '/v1.0/patients/profile/share' => 'abdm_callback#share_abha'
  post '/v0.5/care-contexts/discover' => 'abdm_callback#on_discover'
  post '/v0.5/links/link/on-add-contexts' => 'abdm_callback#on_add_context'
  post '/v0.5/health-information/hip/on-request' => 'abdm_callback#on_request'
  post '/v0.5/consents/hip/notify' => 'abdm_callback#on_notify_hip'
  post '/v0.5/consents/hiu/notify' => 'abdm_callback#on_notify_hiu'
  post '/v0.5/health-information/hiu/on-request' => 'abdm_callback#hiu_on_data_request'
  post '/v0.5/health-information/hip/request' => 'abdm_callback#share_bundle_for_care_context'
  post '/data/push' => 'abdm_callback#receive_bundle_for_care_context'
  post '/v0.5/consent-requests/on-init' => 'abdm_callback#on_init_consent'
  post '/v0.5/consents/on-fetch' => 'abdm_callback#fetch_consent_details'
  get '/api/request' => 'abdm_callback#request_health_data'
  get '/api/init-consent' => 'abdm_callback#init_consent'

  namespace 'api' do
    namespace 'v2' do
      get 'sync/:last_down_sync_time' => 'down_sync#sync'
      post 'areas' => 'area#create'
      put 'areas/:id' => 'area#update'
      put 'villages/:id' => 'village#update'
      post 'villages' => 'village#create'
      post 'check-village-fields' => 'village#check_village_field'
      delete 'areas/:id' => 'area#destroy'
      get 'state/:lgd_code' => 'geography#state'
      get 'district/:id' => 'geography#district'
      get 'block/:id' => 'geography#block'
      get 'phc/:id' => 'geography#phc'
      get 'sub-center/:id' => 'geography#sub_center'
      get 'specializations' => 'specialization#get'
      get 'organizations/:organization_type_id' => 'user_organization#organizations'
      get 'organization-levels/:organization_id' => 'user_organization#organization_levels'
      get 'organization-designations/:organization_id/:organization_level_id' => 'user_organization#organization_designations'
      resource :user, only: [] do
        get 'profile' => 'health_worker#profile'
        post 'register' => 'health_worker#create'
        post 'health-official/register' => 'health_official#create'
        post 'registration-status' => 'health_worker#registration_status'
        post 'check-user-fields' => 'health_worker#check_user_field'
        post 'send-otp' => 'user#send_otp'
        post 'resend-otp' => 'user#resend_otp'
        post 'verify-otp' => 'user#verify_otp'
        post 'reset-password' => 'user#reset_password'
      end
    end
  end


  namespace 'api' do
    namespace 'v1' do
      get 'medicine-stats' => 'medicine_stats#index'
      get 'sync/:last_down_sync_time' => 'down_sync#sync'
      # get 'seed-data/master' => 'seed_data#master'
      # get 'seed-data/opd' => 'seed_data#opd'
      get 'seed-data/master' => 'dhs_seed_data#master'
      get 'seed-data/dhs' => 'dhs_seed_data#dhs'
      get 'people/show/:id' => 'firebase_messaging#get_person'
      get 'medicine_dispatches/show/:id' => 'firebase_messaging#get_medicine_dispatch'
      post 'people' => 'person#create'
      post 'person-allergies' => 'person_allergy#create'
      post 'opd-chief-concerns' => 'opd_chief_concern#create'
      post 'person-habits' => 'person_habit#create'
      post 'opd-lab-tests' => 'opd_lab_test#create'
      post 'person-medical-conditions' => 'person_medical_condition#create'
      post 'opd-visits' => 'opd_visit#create'
      post 'opd-vital-examinations' => 'opd_vital_examination#create'
      post 'opd-prescriptions' => 'opd_prescription#create'
      post 'opd-diagnoses' => 'opd_diagnosis#create'
      post 'wellness-activities' => 'wellness_activities#create'
      post 'trainings' => 'trainings#create'
      post 'meetings' => 'meetings#create'
      post 'medicine_dispatches' => 'medicine_dispatch#create'
      post 'medicine_warehouses' => 'medicine_warehouse#create'
      post 'general-visits' => 'general_visit#create'
      post 'inventories' => 'inventory#create'
      post 'outreach-activity-images' => 'outreach_activity_image#upload'
      post 'image-upload' => 'image_upload#upload'
      delete 'image-upload' => 'image_upload#delete_upload'
      post 'prescription-refills' => 'prescription_refill#create'
      post 'lab-test-visits' => 'lab_test_visit#create'
      post 'face-prints' => 'face_print#create'
      post 'hamlets' => 'hamlet#create'
      post 'houses' => 'house#create'
      post 'families' => 'family#create'
      post 'family-types' => 'family_type#create'
      post 'family-house-ownerships' => 'family_house_ownership#create'
      post 'family-house-structures' => 'family_house_structure#create'
      post 'family-toilet-statuses' => 'family_toilet_status#create'
      post 'family-toilet-status-ques' => 'family_toilet_status_que#create'
      post 'family-drinking-waters' => 'family_drinking_water#create'
      post 'family-electricities' => 'family_electricity#create'
      post 'family-cooking-fuels' => 'family_cooking_fuel#create'
      post 'family-transport-vehicles' => 'family_transport_vehicle#create'
      post 'family-nfsas' => 'family_nfsa#create'
      post 'family-govt-schemes' => 'family_govt_scheme#create'
      post 'family-health-insurance-schemes' => 'family_health_insurance_scheme#create'
      post 'personal-enrollment-educations' => 'personal_enrollment_education#create'
      post 'personal-education-statuses' => 'personal_education_status#create'
      post 'personal-school-details' => 'personal_school_detail#create'
      post 'personal-occupations' => 'personal_occupation#create'
      post 'personal-occupation-risks' => 'personal_occupation_risk#create'
      post 'personal-health-insurance-schemes' => 'personal_health_insurance_scheme#create'
      post 'personal-govt-schemes' => 'personal_govt_scheme#create'
      post 'personal-birth-defects' => 'personal_birth_defect#create'
      post 'personal-health-behaviours' => 'personal_health_behaviour#create'
      post 'personal-diagnosed-diseases' => 'personal_diagnosed_disease#create'
      post 'personal-differently-ableds' => 'personal_differently_abled#create'
      post 'personal-ipds' => 'personal_ipd#create'
      post 'personal-opds' => 'personal_opd#create'
      get 'generate-keys' => 'encryption#generate_keys'
      post 'key-exchange' => 'encryption#compute_shared_secret'
      post 'ipd-hospitalization-frequencies' => 'ipd_hospitalization_frequency#create'
      post 'ipd-nature-treatments' => 'ipd_nature_treatment#create'
      post 'opd-nature-treatments' => 'opd_nature_treatment#create'
      post 'ipd-advices' => 'ipd_advice#create'
      post 'opd-treatments' => 'opd_treatment#create'
      post 'couples' => 'couple#create'
      delete 'couples' => 'couple#destroy'
      delete 'ipd-nature-treatments' => 'ipd_nature_treatment#destroy'
      delete 'opd-nature-treatments' => 'opd_nature_treatment#destroy'
      delete 'ipd-advices' => 'ipd_advice#destroy'
      delete 'opd-treatments' => 'opd_treatment#destroy'
      delete 'ipd-hospitalization-frequencies' => 'ipd_hospitalization_frequency#destroy'
      delete 'opd-chief-concerns' => 'opd_chief_concern#destroy'
      delete 'person-allergies' => 'person_allergy#destroy'
      delete 'person-medical-conditions' => 'person_medical_condition#destroy'
      delete 'opd-vital-examinations' => 'opd_vital_examination#destroy'
      delete 'opd-lab-tests' => 'opd_lab_test#destroy'
      delete 'opd-visits' => 'opd_visit#destroy'
      delete 'person-habits' => 'person_habit#destroy'
      delete 'opd-prescriptions' => 'opd_prescription#destroy'
      delete 'opd-diagnoses' => 'opd_diagnosis#destroy'
      delete 'people' => 'person#destroy'
      delete 'wellness-activities' => 'wellness_activities#destroy'
      delete 'meetings' => 'meetings#destroy'
      delete 'trainings' => 'trainings#destroy'
      delete 'general-visits' => 'general_visit#destroy'
      delete 'prescription-refills' => 'prescription_refill#destroy'
      delete 'lab-test-visits' => 'lab_test_visit#destroy'
      delete 'face-prints' => 'face_print#destroy'
      delete 'hamlets' => 'hamlet#destroy'
      delete 'houses' => 'house#destroy'
      delete 'families' => 'family#destroy'
      delete 'family-types' => 'family_type#destroy'
      delete 'family-house-ownerships' => 'family_house_ownership#destroy'
      delete 'family-house-structures' => 'family_house_structure#destroy'
      delete 'family-toilet-statuses' => 'family_toilet_status#destroy'
      delete 'family-toilet-status-ques' => 'family_toilet_status_que#destroy'
      delete 'family-drinking-waters' => 'family_drinking_water#destroy'
      delete 'family-electricities' => 'family_electricity#destroy'
      delete 'family-cooking-fuels' => 'family_cooking_fuel#destroy'
      delete 'family-transport-vehicles' => 'family_transport_vehicle#destroy'
      delete 'family-nfsas' => 'family_nfsa#destroy'
      delete 'family-govt-schemes' => 'family_govt_scheme#destroy'
      delete 'family-health-insurance-schemes' => 'family_health_insurance_scheme#destroy'
      delete 'personal-enrollment-educations' => 'personal_enrollment_education#destroy'
      delete 'personal-education-status' => 'personal_education_status#destroy'
      delete 'personal-school-details' => 'personal_school_detail#destroy'
      delete 'personal-occupations' => 'personal_occupation#destroy'
      delete 'personal-occupation-risks' => 'personal_occupation_risk#destroy'
      delete 'personal-health-insurance-schemes' => 'personal_health_insurance_scheme#destroy'
      delete 'personal-govt-schemes' => 'personal_govt_scheme#destroy'
      delete 'personal-birth-defects' => 'personal_birth_defect#destroy'
      delete 'personal-health-behaviours' => 'personal_health_behaviour#destroy'
      delete 'personal-diagnosed-diseases' => 'personal_diagnosed_disease#destroy'
      delete 'personal-differently-ableds' => 'personal_differently_abled#destroy'
      delete 'personal-ipds' => 'personal_ipd#destroy'
      delete 'personal-opds' => 'personal_opd#destroy'
      resource :health_facility, only: [] do
        post 'location/:id' => 'health_facility#update_lat_long'
      end
      resource :session, only: [] do
        post 'login' => 'session#create'
        delete 'logout' => 'session#destroy'
      end
      resource :user, only: [] do
        # post 'attendance/punch-in/:id' => 'user#punch_in'
        # post 'attendance/punch-out/:id' => 'user#punch_out'
        post 'attendance/punch-in-out/:id' => 'user#single_punch_in_out'
        post 'attendance/multiple-punch-in-out' => 'user#multiple_punch_in_out'
      end
      resource :firebase_messaging, only: [] do
        post 'fcm-token', to: 'firebase_messaging#store_fcm_token'
        post 'push' => 'firebase_messaging#push'
      end
    end
  end
end